const esc = v => String(v ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(path,options={}){const r=await fetch('/api/'+path,{...options,headers:{'X-Demo-Role':currentUser?.role||'customer','X-Demo-Email':currentUser?.email||'rieke@andallo.com',...options.headers}});const data=await r.json();if(!r.ok)throw Error(data.error||'Gagal menyimpan. Coba lagi.');return data;}
let savedReviewsSnapshot=null;
async function loadBookings(){try{bookings=await api('bookings');const reviews=await api('reviews');const snapshot=JSON.stringify(reviews);if(snapshot!==savedReviewsSnapshot){savedReviewsSnapshot=snapshot;for(const p of providers){p.reviews=p.reviews.filter(r=>!r.bookingId);p.reviews.unshift(...reviews.filter(r=>r.providerId===p.id).map(r=>({bookingId:r.bookingId,name:r.name,rating:r.rating,comment:r.comment})));p.rating=+(p.reviews.reduce((sum,r)=>sum+r.rating,0)/p.reviews.length).toFixed(1);}renderHomeProviders();applyFilters();if(document.getElementById('page-bandingkan').classList.contains('active'))renderComparisonPage();if(document.getElementById('page-detail').classList.contains('active')&&currentDetailId)openProviderDetail(currentDetailId);}if(currentUser){renderCustomerDashboard();renderAdminDashboard();}}catch(e){showToast(e.message);}}
const oldLogin=handleLoginSubmit;handleLoginSubmit=function(e){oldLogin(e);if(currentUser)loadBookings();};
const oldDemo=quickDemoLogin;quickDemoLogin=function(email){oldDemo(email);closeModal('modalMasuk');loadBookings();};
const oldVerify=confirmVerification;confirmVerification=function(){oldVerify();loadBookings();};
const oldDash=goToDashboard;goToDashboard=function(){oldDash();loadBookings();};
handleBookingSubmit=async function(e){e.preventDefault();const button=e.target.querySelector('[type="submit"]');if(button)button.disabled=true;try{const b=await api('bookings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({providerId:currentDetailId,date:document.getElementById('bookingDate').value,time:document.getElementById('bookingTime').value})});await loadBookings();closeModal('modalBooking');showToast('Pesanan terkirim. Tunggu penyedia menerima sebelum membayar.');showPage('dashboard-customer');}catch(e){showToast(e.message);}finally{if(button)button.disabled=false;}};
const originalOpenBooking=openBookingModal;openBookingModal=function(id){originalOpenBooking(id);document.getElementById('bookingDate').min=new Date().toLocaleDateString('en-CA');};
const baseCustomer=renderCustomerDashboard;renderCustomerDashboard=function(){baseCustomer();if(!currentUser)return;const rows=[...document.getElementById('customerBookingList').children];const list=bookings.filter(b=>b.customerEmail===currentUser.email).sort((a,b)=>b.id-a.id);list.forEach((b,i)=>{rows[i]?.insertAdjacentHTML('beforeend',`<div class="w-full"><p class="payment-steps">1. Penyedia menerima → 2. Unggah bukti → 3. Verifikasi → 4. Layanan diproses</p>${b.status==='PENDING'?'<p class="text-sm text-gray-600">Menunggu konfirmasi penyedia. Pembayaran belum dibuka.</p>':`<button class="pay-button" onclick="openPayment(${b.id})">${b.status==='AWAITING_PAYMENT'?'Unggah bukti pembayaran':'Detail pembayaran'}</button>`}</div>`);});};
renderAdminDashboard=function(){if(!currentUser)return;const admin=currentUser.role==='admin';document.getElementById('adminDashTitle').textContent=admin?'Dashboard Admin':'Dashboard Mitra Jasa';document.getElementById('adminDashSub').textContent='Terima pesanan, periksa pembayaran, lalu proses layanan. Data pesanan pada halaman ini berasal dari penggunaan akun contoh.';const list=bookings.filter(b=>admin||providers.find(p=>p.id===b.providerId)?.providerEmail===currentUser.email).sort((a,b)=>b.id-a.id);document.getElementById('adminBookingTable').innerHTML=list.length?list.map(b=>{const p=providers.find(p=>p.id===b.providerId);let action='';if(b.status==='PENDING')action=`<button class="pay-button" onclick="updateBookingStatus(${b.id},'AWAITING_PAYMENT')">Terima pesanan</button>`;if(b.status==='AWAITING_PAYMENT')action='<span>Menunggu bukti pelanggan</span>';if(b.status==='PAYMENT_REVIEW')action=admin?`<button class="pay-button" onclick="openPayment(${b.id})">Periksa bukti</button>`:'Menunggu verifikasi admin';if(b.status==='DIMULAI')action=`<button class="pay-button" onclick="updateBookingStatus(${b.id},'ON_PROGRESS')">Proses layanan</button>`;if(b.status==='ON_PROGRESS')action=`<button class="pay-button" onclick="updateBookingStatus(${b.id},'SELESAI')">Selesaikan</button>`;return `<tr class="border-b"><td class="p-4">${esc(b.customerEmail)}</td><td class="p-4">${esc(p?.name)}</td><td class="p-4">${esc(b.date)} ${esc(b.time)}</td><td class="p-4">Rp${b.total.toLocaleString('id-ID')}</td><td class="p-4">${STATUS_LABEL[b.status]}</td><td class="p-4">${action}${b.status==='PENDING'?`<button class="block mt-2 text-red-700" onclick="updateBookingStatus(${b.id},'CANCELLED')">Tolak pesanan</button>`:''}</td></tr>`;}).join(''):'<tr><td colspan="6" class="p-8 text-center">Belum ada pesanan masuk.</td></tr>';};
updateBookingStatus=async function(id,status){try{await api('bookings/'+id,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status})});await loadBookings();closeModal('modalPayment');showToast('Status pesanan berhasil diperbarui.');}catch(e){showToast(e.message);}};
document.body.insertAdjacentHTML('beforeend','<div id="modalPayment" class="modal-overlay" role="dialog" aria-modal="true" aria-labelledby="paymentTitle"><div class="modal-box bg-white rounded-2xl p-6 w-full max-w-xl"><div class="flex justify-between items-center"><h2 id="paymentTitle" class="text-xl font-bold">Pembayaran pesanan</h2><button onclick="closeModal(\'modalPayment\')" aria-label="Tutup pembayaran" class="p-3">✕</button></div><div id="paymentContent"></div></div></div>');
function openPayment(id){const b=bookings.find(x=>x.id===id);if(!b)return;const upload=b.status==='AWAITING_PAYMENT'&&currentUser.role==='customer';document.getElementById('paymentContent').innerHTML=`<div class="payment-panel"><h3>Rp${b.total.toLocaleString('id-ID')}</h3><p>${esc(providers.find(p=>p.id===b.providerId)?.name)} · #${b.id}</p><p class="payment-status">${STATUS_LABEL[b.status]}</p><p>Pembayaran manual — demo. Rekening tujuan belum dikonfigurasi. Gunakan gambar contoh untuk menguji alur, tanpa transfer uang.</p>${b.rejection?`<p class="text-red-700">Bukti ditolak: ${esc(b.rejection)}. Silakan unggah ulang.</p>`:''}${b.proof?`<a href="/api/bookings/${b.id}/proof" target="_blank" rel="noopener" class="underline text-emerald-700">Lihat bukti yang diunggah</a>`:''}${upload?`<form onsubmit="uploadPayment(event,${b.id})"><label class="block my-3" for="proofFile">Bukti pembayaran (JPG/PNG, maksimal 5 MB)</label><input id="proofFile" type="file" accept="image/jpeg,image/png" required><div class="payment-actions"><button type="submit">Kirim bukti pembayaran</button></div><p id="uploadFeedback" role="status"></p></form>`:''}${currentUser.role==='admin'&&b.status==='PAYMENT_REVIEW'?`<div class="payment-actions"><button onclick="updateBookingStatus(${b.id},'DIMULAI')">Verifikasi pembayaran</button><button class="secondary" onclick="rejectProof(${b.id})">Tolak & minta unggah ulang</button></div>`:''}</div>`;openModal('modalPayment');}
async function uploadPayment(e,id){e.preventDefault();const f=document.getElementById('proofFile').files[0];const feedback=document.getElementById('uploadFeedback');if(!f||!['image/jpeg','image/png'].includes(f.type)||f.size>5*1024*1024){feedback.textContent='Pilih gambar JPG/PNG maksimal 5 MB.';return;}const button=e.target.querySelector('button');button.disabled=true;feedback.textContent='Mengunggah bukti…';try{await api('bookings/'+id+'/proof',{method:'POST',headers:{'Content-Type':f.type},body:f});await loadBookings();openPayment(id);showToast('Bukti tersimpan. Menunggu verifikasi admin.');}catch(error){feedback.textContent=error.message;button.disabled=false;}}
async function rejectProof(id){const reason=prompt('Alasan penolakan bukti pembayaran:');if(!reason?.trim())return;try{await api('bookings/'+id,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:'AWAITING_PAYMENT',rejection:reason.trim()})});await loadBookings();openPayment(id);}catch(e){showToast(e.message);}}
const originalChat=sendChatMessage;sendChatMessage=async function(e){e.preventDefault();const input=document.getElementById('chatInput'),value=input.value.trim();if(!value)return;try{await api('bookings/'+currentChatBookingId+'/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:value})});input.value='';await loadBookings();renderChatMessages();}catch(e){showToast(e.message);}};
loadBookings();
submitRating=async function(e){e.preventDefault();if(!selectedStars){showToast('Pilih jumlah bintang dulu.');return;}const button=e.target.querySelector('[type="submit"]');button.disabled=true;try{await api('bookings/'+currentRatingBookingId+'/rating',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({stars:selectedStars,text:document.getElementById('ratingUlasan').value.trim(),name:currentUser.name})});savedReviewsSnapshot=null;await loadBookings();closeModal('modalRating');showToast('Ulasan tersimpan. Terima kasih!');}catch(error){showToast(error.message);}finally{button.disabled=false;}};
document.addEventListener('keydown',e=>{if(e.key==='Escape')document.querySelectorAll('.modal-overlay.open').forEach(m=>closeModal(m.id));});
const baseChat=renderChat;renderChat=function(){baseChat();if(!document.getElementById('chatTemplates'))document.getElementById('chatInput').closest('form').insertAdjacentHTML('beforebegin','<div id="chatTemplates" class="flex gap-2 flex-wrap p-3"></div>');document.getElementById('chatTemplates').innerHTML=['Halo, kapan layanan ini diproses?','Kapan penyedia jasa menghubungi saya?','Bagaimana cara bayar?'].map(q=>`<button class="px-3 py-2 rounded-full border text-sm" onclick="document.getElementById(\'chatInput\').value=this.textContent">${q}</button>`).join('');};
window.addEventListener('focus',()=>{if(currentUser)loadBookings();});
